import type { InferInsertModel } from "drizzle-orm";
import { facts } from "../schema";

export type NewFact = InferInsertModel<typeof facts>;

const date = (value: string): Date => new Date(`${value}T00:00:00.000Z`);

export const FACTS: NewFact[] = [
  {
    id: "fact-arbeitslose-jan-2026",
    category: "arbeitsmarkt",
    valueLabel: "3,085 Mio. Arbeitslose im Januar 2026",
    valueNumeric: "3.085",
    unit: "Mio.",
    period: "2026-01",
    sourceName: "Bundesagentur für Arbeit",
    sourceUrl: "https://www.arbeitsagentur.de/presse/2026-05-arbeitsmarkt-im-januar-2026",
    sourceStand: "30. Januar 2026",
    retrievedAt: date("2026-05-23"),
  },
  {
    id: "fact-iw-inflation-2026",
    category: "finanzen",
    valueLabel: "IW Köln Prognose Jahresinflation 2026 rund 2 %",
    valueNumeric: "2",
    unit: "Prozent YoY",
    period: "2026",
    sourceName: "IW Köln",
    sourceUrl: "https://www.iwkoeln.de/presse/pressemitteilungen/michael-groemling-bip-waechst-2026-um-knapp-ein-prozent.html",
    sourceStand: "5. Dezember 2025",
    retrievedAt: date("2026-05-23"),
  },
  {
    id: "fact-wachstum-2026-halbiert",
    category: "konjunktur",
    valueLabel: "Wachstumsprognose 2026 von 1,0 % auf 0,5 % halbiert",
    valueNumeric: "0.5",
    unit: "Prozent BIP",
    period: "2026",
    sourceName: "Capital",
    sourceUrl: "https://www.capital.de/wirtschaft-politik/wachstum-2026--regierung-halbiert-prognose-wegen-irankrieg-37333956.html",
    sourceStand: "Mai 2026",
    retrievedAt: date("2026-05-13"),
  },
  {
    id: "fact-fao-food-2026-03",
    category: "lebensmittel",
    valueLabel: "FAO Food Price Index +2,4 % März 2026; Zucker +7,2 %",
    valueNumeric: "2.4",
    unit: "Prozent MoM; Zucker +7,2 %",
    period: "2026-03",
    sourceName: "FAO Food Price Index",
    sourceUrl: "https://www.fao.org/worldfoodsituation/foodpricesindex",
    sourceStand: "März 2026",
    retrievedAt: date("2026-05-14"),
  },
  {
    id: "fact-bsi-stadtwerke-97",
    category: "infrastruktur",
    valueLabel: "97 % Stadtwerke von Cyberangriffen betroffen (BSI)",
    valueNumeric: "97",
    unit: "Prozent",
    period: "2025-11",
    sourceName: "BSI",
    sourceUrl: "https://www.bsi.bund.de/SharedDocs/Downloads/DE/BSI/Publikationen/Lageberichte/Lagebericht2025_Achtseiter.html",
    sourceStand: "November 2025",
    retrievedAt: date("2026-05-14"),
  },
  {
    id: "fact-vertrauen-89",
    category: "gesellschaft",
    valueLabel: "89 % erwarten weiteren Vertrauensverlust (Stiftung Zukunftsfragen)",
    valueNumeric: "89",
    unit: "Prozent",
    period: "2026",
    sourceName: "Stiftung für Zukunftsfragen",
    sourceUrl: "https://www.stiftungfuerzukunftsfragen.de/wie-blicken-die-buerger-auf-das-jahr-2026/",
    sourceStand: "2026",
    retrievedAt: date("2026-05-13"),
  },
  {
    id: "fact-destatis-kraftstoffe-2026-04",
    category: "mobilitaet",
    valueLabel: "Destatis: VPI April 2026 +2,9 %, Kraftstoffe +26,2 %, Heizöl +55,1 % YoY",
    valueNumeric: "26.2",
    unit: "Prozent YoY; VPI +2,9 %; Heizöl +55,1 %",
    period: "2026-04",
    sourceName: "Destatis",
    sourceUrl: "https://www.destatis.de/DE/Presse/Pressemitteilungen/2026/05/PD26_161_611.html",
    sourceStand: "12. Mai 2026 / April 2026",
    retrievedAt: date("2026-05-23"),
  },
  {
    id: "fact-tankrabatt-17-cent",
    category: "governance",
    valueLabel: "Tankrabatt 17 Cent / 14,04 Cent Energiesteuer",
    valueNumeric: "14.04",
    unit: "Cent Energiesteuer-Senkung; 17 Cent kommuniziert",
    period: "2022",
    sourceName: "Bundestag — Energiesteuer-Senkung",
    sourceUrl: "https://www.bundestag.de/dokumente/textarchiv/2026/kw17-pa-finanzen-1166336",
    sourceStand: "April 2026",
    retrievedAt: date("2026-05-19"),
  },
  {
    id: "fact-gasspeicher-winter-2026",
    category: "energie",
    valueLabel: "Gasspeicher unter Vorjahresniveau, Winter 2026/27",
    valueNumeric: null,
    unit: "qualitativ",
    period: "2026/27",
    sourceName: "Bundesnetzagentur (via AGSI/GIE)",
    sourceUrl: "https://www.bundesnetzagentur.de/DE/Fachthemen/ElektrizitaetundGas/Versorgungssicherheit/aktuelle_gasversorgung/start.html",
    sourceStand: "2026",
    retrievedAt: date("2026-05-19"),
  },
  {
    id: "fact-bfarm-engpaesse-2026",
    category: "gesundheit",
    valueLabel: "BfArM Lieferengpässe Wirkstoffe 2026",
    valueNumeric: null,
    unit: "qualitativ",
    period: "2026",
    sourceName: "BfArM",
    sourceUrl: "https://www.bfarm.de/DE/Arzneimittel/Arzneimittelinformationen/Lieferengpaesse/_verteilerseite.html?nn=471282",
    sourceStand: "2026",
    retrievedAt: date("2026-05-21"),
  },
  {
    id: "fact-post-schlichtung-2026",
    category: "logistik",
    valueLabel: "Bundesnetzagentur: 4.804 Post- und 5.524 TK-Schlichtungsanträge 2025",
    valueNumeric: "4804",
    unit: "Anträge; Post 4.804; TK 5.524",
    period: "2025",
    sourceName: "Bundesnetzagentur — Schlichtung Post",
    sourceUrl: "https://www.bundesnetzagentur.de/SharedDocs/Pressemitteilungen/DE/2026/20260202_Schlichtung_TK_Post.html",
    sourceStand: "2. Februar 2026",
    retrievedAt: date("2026-05-23"),
  },
];
